# Generated by Django 3.1.14 on 2023-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20230808_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_language',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Мова'),
        ),
    ]
